# This is a basic workflow to help you get started with Actions

name: Test build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - v**
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test_build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v1.1.11
        with:
          ocaml-version: '4.11.2'

      - name: Build the program
        run: opam install . -y
